org: andymarch
app: request-context-token-hook
service: okta-request-context-hook

frameworkVersion: '2 || 3'


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  environment:
    ORG: ${param:org}
    ORG_TOKEN:  ${param:org_token}
    BUCKET: ${param:bucket-name}
    ISSUER: ${param:issuer-uri}

functions:
  hello:
    handler: handler.hello
    events:
    - http:
        path: /context
        method: post
